export interface SpellData {
  id: string;
  name: string;
  school: string;
  sphere?: string;
  level: number;
  range: string;
  components: string;
  duration: string;
  castingTime: string;
  areaOfEffect: string;
  savingThrow: string;
  summary: string;
  description: string;
  spellClass: 'priest' | 'wizard' | 'all';
}

export const SPELLS: SpellData[] = [
  {
    id: 'altruism',
    name: 'Altruism',
    school: 'Alteration',
    sphere: 'Thought',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '1 round/level',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Target gains +1 to attack and saving throws when acting to protect others.',
    description: 'This spell fills the target with altruistic resolve. For the duration, the target gains a +1 bonus to attack rolls and saving throws made while defending or aiding another creature within 10 feet.',
    spellClass: 'priest',
  },
  {
    id: 'analyze-balance',
    name: 'Analyze Balance',
    school: 'Divination',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S, M',
    duration: 'Instantaneous',
    castingTime: '1 round',
    areaOfEffect: '10-yard radius',
    savingThrow: 'None',
    summary: 'Reveals whether the area tends toward Law, Chaos, Good, Evil, or is Neutral.',
    description: 'By casting this spell the priest learns the general alignment tendency of an area, creature, or object within range. The result indicates a dominant alignment force (Lawful, Chaotic, Good, Evil) or Neutral balance. It does not reveal individual alignments. Material component: a perfectly balanced scale made of silver.',
    spellClass: 'priest',
  },
  {
    id: 'astral-celerity',
    name: 'Astral Celerity',
    school: 'Alteration',
    sphere: 'Astral',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '1 turn',
    castingTime: '4',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Doubles movement rate on the Astral Plane.',
    description: 'This spell doubles the base movement rate of one creature while it is on the Astral Plane. It has no effect on the Prime Material or other planes.',
    spellClass: 'priest',
  },
  {
    id: 'battlefate',
    name: 'Battlefate',
    school: 'Divination',
    sphere: 'War',
    level: 1,
    range: '30 yards',
    components: 'V, S, M',
    duration: 'Instantaneous',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Reveals whether target will win, lose, or draw in next combat.',
    description: 'The priest perceives a brief flash of fate regarding one creature\'s next combat. The DM secretly rolls d6: 1-2 defeat, 3-4 draw/survival, 5-6 victory. The priest communicates only this omen to the target. Material component: a coin.',
    spellClass: 'priest',
  },
  {
    id: 'beastmask',
    name: 'Beastmask',
    school: 'Illusion',
    sphere: 'Animal',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 turn/level',
    castingTime: '4',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Caster appears as a non-threatening animal to real animals.',
    description: 'While under this spell, natural (non-magical) animals perceive the caster as a harmless member of their own species or a familiar animal. Animals will not attack the caster unless attacked first or under magical compulsion. Material component: a tuft of fur from the target animal type.',
    spellClass: 'priest',
  },
  {
    id: 'bless',
    name: 'Bless',
    school: 'Conjuration',
    sphere: 'All',
    level: 1,
    range: '60 yards',
    components: 'V, S, M',
    duration: '6 rounds',
    castingTime: '1 round',
    areaOfEffect: '50-ft. cube',
    savingThrow: 'None',
    summary: '+1 to attack rolls and morale for allies not yet in melee.',
    description: 'Upon uttering the Bless spell, the caster raises the morale of friendly creatures and increases their attack dice rolls by +1. The spell is ineffective on creatures already engaged in melee. The reverse, Curse, causes -1 penalty to attack rolls and morale for enemies in the area. Material component: holy water.',
    spellClass: 'priest',
  },
  {
    id: 'blessed-watchfulness',
    name: 'Blessed Watchfulness',
    school: 'Divination',
    sphere: 'Guardian',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '8 hours',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Target cannot be surprised and gains +2 to surprise rolls while on watch.',
    description: 'This spell keeps one creature alert and resistant to surprise for 8 hours—ideal for guards or sentinels. The target cannot be surprised and adds +2 to any dice rolls related to detecting intruders or ambushes.',
    spellClass: 'priest',
  },
  {
    id: 'calculate',
    name: 'Calculate',
    school: 'Divination',
    sphere: 'Numbers',
    level: 1,
    range: '0',
    components: 'V, S',
    duration: 'Instantaneous',
    castingTime: '1',
    areaOfEffect: 'Caster',
    savingThrow: 'None',
    summary: 'Instantly and accurately counts or measures one discrete quantity.',
    description: 'The priest mentally determines any single countable or measurable quantity within sight—the number of coins in a pile, exact weight of an object, number of creatures in a room, etc. The result is always accurate. Does not reveal hidden or invisible items.',
    spellClass: 'priest',
  },
  {
    id: 'call-upon-faith',
    name: 'Call Upon Faith',
    school: 'Evocation',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V',
    duration: 'Instantaneous',
    castingTime: '1',
    areaOfEffect: 'Caster',
    savingThrow: 'None',
    summary: '+3 bonus to one roll if the priest has acted in accordance with their faith recently.',
    description: 'The priest calls on divine favor for one roll (attack, saving throw, ability check, or proficiency check) immediately after casting. If the DM judges the priest has recently upheld their deity\'s tenets, the roll gains +3. If the priest has violated their faith, the spell fails and may cause -1 instead.',
    spellClass: 'priest',
  },
  {
    id: 'calm-animals',
    name: 'Calm Animals',
    school: 'Enchantment',
    sphere: 'Animal',
    level: 1,
    range: '60 yards',
    components: 'V, S',
    duration: '1 round/level',
    castingTime: '1',
    areaOfEffect: 'Up to 2d4 HD of animals',
    savingThrow: 'Neg.',
    summary: 'Calms normal animals; they stand passive and do not attack.',
    description: 'This spell soothes and pacifies normal animals (not magical beasts or trained war animals). Up to 2d4 HD worth of animals within range must save vs. spell or become calm and passive for the duration. Calmed animals will not attack unless attacked. The effect ends early if the animals are attacked or startled.',
    spellClass: 'priest',
  },
  {
    id: 'combine',
    name: 'Combine',
    school: 'Evocation',
    sphere: 'All',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: 'Special',
    castingTime: '1 round',
    areaOfEffect: 'Circle of priests',
    savingThrow: 'None',
    summary: 'Links 2–5 priests to boost one caster\'s effective level for turning or spells.',
    description: 'Two to five priests join hands in a circle; one is designated the primary caster. For each additional priest in the circle, the primary\'s effective level increases by 1 for purposes of turning undead or casting one spell. All participating priests except the primary expend their actions for the round. The circle breaks if any participant moves or is attacked.',
    spellClass: 'priest',
  },
  {
    id: 'command',
    name: 'Command',
    school: 'Enchantment',
    sphere: 'All',
    level: 1,
    range: '30 yards',
    components: 'V',
    duration: '1 round',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'Special',
    summary: 'One-word command obeyed immediately unless target has 6+ HD or INT 13+.',
    description: 'The priest utters a single word of command (e.g., "flee," "halt," "fall," "drop," "sleep"). The target must obey literally and immediately for 1 round. Creatures with 6 or more HD or Intelligence 13+ are unaffected. Undead are immune. Suicidal commands are also ignored.',
    spellClass: 'priest',
  },
  {
    id: 'courage',
    name: 'Courage',
    school: 'Enchantment',
    sphere: 'War',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '1 turn + 1 round/level',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Target is immune to fear effects and gains +1 morale bonus.',
    description: 'The recipient becomes immune to all fear effects (natural or magical) for the duration and gains a +1 bonus to morale-based rolls. Any existing fear condition is suppressed (not removed) for the duration.',
    spellClass: 'priest',
  },
  {
    id: 'create-water',
    name: 'Create Water',
    school: 'Alteration',
    sphere: 'Elemental (Water)',
    level: 1,
    range: '30 yards',
    components: 'V, S, M',
    duration: 'Permanent',
    castingTime: '1 round',
    areaOfEffect: 'Up to 27 cubic feet',
    savingThrow: 'None',
    summary: 'Creates 4 gallons of clean water per level (max 112 gallons).',
    description: 'This spell generates wholesome, drinkable water—4 gallons per caster level (maximum 112 gallons at 28th level). The water appears in an open container or on the ground. The reverse, Destroy Water, eliminates the same volume of water. Material component: a drop of water (or a pinch of dust for the reverse).',
    spellClass: 'priest',
  },
  {
    id: 'cure-light-wounds',
    name: 'Cure Light Wounds',
    school: 'Necromancy',
    sphere: 'Healing',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: 'Permanent',
    castingTime: '5',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Heals 1d8 hp. Reverse (Cause Light Wounds) inflicts 1d8 hp on touch.',
    description: 'When the priest lays hands on a creature and casts this spell, between 1 and 8 hit points of damage are healed. It will not raise the recipient above their maximum hit points. The reverse, Cause Light Wounds, inflicts 1d8 points of damage on a successful touch attack (saving throw for half).',
    spellClass: 'priest',
  },
  {
    id: 'detect-evil',
    name: 'Detect Evil',
    school: 'Divination',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S, M',
    duration: '1 turn + 5 rounds/level',
    castingTime: '1 round',
    areaOfEffect: '10 ft. × 120 ft. path',
    savingThrow: 'None',
    summary: 'Reveals evil emanations in a 10×120-ft. path ahead of caster.',
    description: 'The priest can sense evil (or good with the reverse) emanations—including enchanted objects, evil intentions, and undead—along a 10-foot-wide, 120-foot-long path. It does not reveal alignment of neutral creatures. The reverse, Detect Good, functions identically for good emanations. Material component: holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'detect-magic',
    name: 'Detect Magic',
    school: 'Divination',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S, M',
    duration: '1 turn',
    castingTime: '1 round',
    areaOfEffect: '10 ft. × 30 ft. path',
    savingThrow: 'None',
    summary: 'Detects magical radiations in a 10×30-ft. path for 1 turn.',
    description: 'The priest can detect magical radiations in the path ahead. Magical items, spell effects, and enchanted creatures glow. The priest can determine the general school of magic with a successful Intelligence check. Material component: holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'detect-poison',
    name: 'Detect Poison',
    school: 'Divination',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S, M',
    duration: '1 turn + 1 round/level',
    castingTime: '4',
    areaOfEffect: '1 creature or object',
    savingThrow: 'None',
    summary: 'Detects presence of poison in one creature or object; chance to identify type.',
    description: 'The priest can determine whether one creature or object has been poisoned or is poisonous. There is a 5% chance per level (max 75%) of identifying the specific type of poison. Material component: a yew leaf.',
    spellClass: 'priest',
  },
  {
    id: 'detect-snares-pits',
    name: 'Detect Snares & Pits',
    school: 'Divination',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S, M',
    duration: '4 rounds/level',
    castingTime: '4',
    areaOfEffect: '10 ft. wide × 40 ft. long path',
    savingThrow: 'None',
    summary: 'Reveals natural and primitive traps (pits, snares, deadfalls) within path.',
    description: 'The priest can detect all natural traps—pits, snares, deadfalls, and similar primitive devices—within the area ahead. It does not detect mechanical traps, spells, or magical wards. Material component: a piece of circlet vine.',
    spellClass: 'priest',
  },
  {
    id: 'dispel-fatigue',
    name: 'Dispel Fatigue',
    school: 'Necromancy',
    sphere: 'Healing',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: 'Permanent',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Removes fatigue; target treated as fully rested for 8 hours.',
    description: 'This spell removes the effects of physical fatigue from one creature, treating it as fully rested. Penalties from exhaustion or forced march are negated for 8 hours, after which normal fatigue resumes. It does not restore hit points or remove magical exhaustion.',
    spellClass: 'priest',
  },
  {
    id: 'emotion-read',
    name: 'Emotion Read',
    school: 'Divination',
    sphere: 'Thought',
    level: 1,
    range: '10 yards',
    components: 'V, S',
    duration: 'Instantaneous',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'Neg.',
    summary: 'Senses the dominant emotion of one creature (fear, anger, joy, etc.).',
    description: 'The caster reads the surface emotional state of one creature within range. The result is one dominant emotion (fear, rage, joy, sorrow, calm, etc.). It does not reveal thoughts or intentions. Creatures that save are unaffected and unaware of the attempt.',
    spellClass: 'priest',
  },
  {
    id: 'endure-cold-heat',
    name: 'Endure Cold/Heat',
    school: 'Alteration',
    sphere: 'Protection',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '1 hour/level',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Creature comfortable in temperatures from -30°F to 130°F; halves environmental damage.',
    description: 'The affected creature can endure temperatures from -30°F to 130°F without discomfort or penalty. If environmental conditions cause damage (extreme cold or heat beyond these ranges), the damage is halved. Does not protect against magical fire or cold attacks.',
    spellClass: 'priest',
  },
  {
    id: 'entangle',
    name: 'Entangle',
    school: 'Alteration',
    sphere: 'Plant',
    level: 1,
    range: '80 yards',
    components: 'V, S, M',
    duration: '1 turn',
    castingTime: '4',
    areaOfEffect: '40-ft. cube',
    savingThrow: 'Neg.',
    summary: 'Plants entwine creatures in area; failed save = entangled, movement 0.',
    description: 'Tall grass, weeds, bushes, and even trees wrap around creatures in the area. Those who fail their saving throw are entangled and cannot move. Those who succeed can move at half speed. Entangled creatures can still attack at -2 penalty. Burning the plants ends the effect. Material component: a drop of water and a piece of humus.',
    spellClass: 'priest',
  },
  {
    id: 'invisibility-to-undead',
    name: 'Invisibility to Undead',
    school: 'Abjuration',
    sphere: 'Necromantic',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '6 rounds',
    castingTime: '4',
    areaOfEffect: '1 creature',
    savingThrow: 'Special',
    summary: 'Undead with fewer than 5 HD cannot perceive the target; higher HD get a save.',
    description: 'Undead with fewer than 5 HD cannot detect or attack the target. Undead with 5–7 HD receive a saving throw to see through the effect; those with 8+ HD are unaffected. The spell ends early if the target attacks or takes hostile action. Material component: the priest\'s holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'light',
    name: 'Light',
    school: 'Alteration',
    sphere: 'Sun',
    level: 1,
    range: '120 yards',
    components: 'V, S',
    duration: '1 hour + 1 turn/level',
    castingTime: '4',
    areaOfEffect: '20-ft. radius globe',
    savingThrow: 'Special',
    summary: 'Creates a 20-ft. radius light source. Cast on eyes: blind until dispelled (save neg.).',
    description: 'This spell creates a globe of light equivalent to torchlight. It can be cast on an object or a point in space. If cast on a creature\'s eyes, that creature must save vs. spell or be blinded until the spell is dispelled. The reverse, Darkness, creates a 15-ft. radius area of magical darkness.',
    spellClass: 'priest',
  },
  {
    id: 'magical-stone',
    name: 'Magical Stone',
    school: 'Enchantment',
    sphere: 'Combat',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '30 minutes or until thrown',
    castingTime: '4',
    areaOfEffect: '3 pebbles',
    savingThrow: 'None',
    summary: 'Enchants 3 pebbles; each hits as +1 weapon dealing 1d4+1 (2d4+2 vs. undead).',
    description: 'Three small pebbles become +1 magical projectiles. Each is hurled by hand (range 30/60/90 ft.) or from a sling. Each hits for 1d4+1 points of damage (2d4+2 against undead). The enchantment ends when the pebbles are thrown or the duration expires. Material component: three small pebbles.',
    spellClass: 'priest',
  },
  {
    id: 'orison',
    name: 'Orison',
    school: 'Conjuration',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S',
    duration: 'Special',
    castingTime: '1 round',
    areaOfEffect: 'Caster',
    savingThrow: 'None',
    summary: 'Minor divine prayer; grants +1 to one roll or minor miraculous effect at DM discretion.',
    description: 'A humble prayer to the priest\'s deity. The DM may grant a minor benefit—a +1 bonus to the next roll, a moment of divine insight, or a small miracle—based on how faithfully the priest has followed their deity\'s code. Overuse may result in no benefit.',
    spellClass: 'priest',
  },
  {
    id: 'protection-from-evil',
    name: 'Protection from Evil',
    school: 'Abjuration',
    sphere: 'Protection',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '3 rounds/level',
    castingTime: '4',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: '+2 AC and saves vs. evil creatures; blocks mental control; bodily contact forbidden for summoned creatures.',
    description: 'This spell creates a magical barrier around the recipient at a distance of 1 foot. The barrier moves with the recipient, providing +2 to AC and saving throws against attacks from evil or evilly aligned creatures. It also prevents bodily contact by summoned or conjured evil creatures. Material component: holy water or holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'purify-food-drink',
    name: 'Purify Food & Drink',
    school: 'Alteration',
    sphere: 'All',
    level: 1,
    range: '30 yards',
    components: 'V, S',
    duration: 'Permanent',
    castingTime: '1 round',
    areaOfEffect: '1 cubic foot/level',
    savingThrow: 'None',
    summary: 'Makes spoiled, poisoned, or contaminated food/drink safe and nutritious.',
    description: 'This spell makes spoiled, rotten, poisonous, or otherwise contaminated food and water pure and suitable for eating and drinking. It does not create food; it only purifies existing food. The reverse, Contaminate Food & Drink, poisons or spoils the same quantity of consumables.',
    spellClass: 'priest',
  },
  {
    id: 'remove-fear',
    name: 'Remove Fear',
    school: 'Abjuration',
    sphere: 'Charm',
    level: 1,
    range: '10 yards',
    components: 'V, S',
    duration: 'Special',
    castingTime: '1',
    areaOfEffect: '1 creature + 1/4 levels',
    savingThrow: 'None',
    summary: 'Removes fear; +4 to saves vs. fear for 1 hour. Reverse causes fear (save or flee 1d4 rounds).',
    description: 'This spell instills courage in the recipient, removing the effects of magical or normal fear. If the target is currently fleeing in fear, it may immediately re-save with a +4 bonus; success ends the fear. The spell also grants +4 to all saving throws against fear effects for 1 hour. The reverse, Cause Fear, causes one creature to flee in panic for 1d4 rounds (saving throw negates).',
    spellClass: 'priest',
  },
  {
    id: 'ring-of-hands',
    name: 'Ring of Hands',
    school: 'Evocation',
    sphere: 'Protection',
    level: 1,
    range: '0',
    components: 'V, S',
    duration: '1 round/level',
    castingTime: '1',
    areaOfEffect: 'Circle of casters',
    savingThrow: 'None',
    summary: 'Up to 10 priests join to create a protective circle; barrier repels undead and evil outsiders.',
    description: 'Up to 10 priests join hands and form a ring. While the ring is unbroken, a protective barrier prevents undead and summoned evil creatures from crossing into the circle. The barrier has no effect on natural evil creatures or humanoids. The ring breaks if any participant releases hands or is incapacitated.',
    spellClass: 'priest',
  },
  {
    id: 'sacred-guardian',
    name: 'Sacred Guardian',
    school: 'Divination',
    sphere: 'Guardian',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Until discharged',
    castingTime: '1 round',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Caster is instantly alerted (anywhere on same plane) when recipient is in mortal danger.',
    description: 'The priest places a magical link on one willing creature. If that creature falls to 0 hit points or is subjected to a death effect, the priest is instantly aware of the danger regardless of distance (as long as both are on the same plane). The spell is discharged after a single alert. Material component: a lock of the recipient\'s hair.',
    spellClass: 'priest',
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    school: 'Abjuration',
    sphere: 'Protection',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '2 rounds + 1 round/level',
    castingTime: '4',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Enemies must save to attack recipient; recipient cannot attack without ending effect.',
    description: 'Any opponent attempting to strike or attack the warded creature must first make a saving throw vs. spell. Failure means they cannot attack that creature this round (they may attack others). Success means the sanctuary is broken and the spell ends for that attacker. The ward ends entirely if the recipient makes any attack or casts a harmful spell. Material component: the priest\'s holy symbol and a small silver mirror.',
    spellClass: 'priest',
  },
  {
    id: 'speak-with-astral-traveler',
    name: 'Speak with Astral Traveler',
    school: 'Divination',
    sphere: 'Astral',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '1 round/level',
    castingTime: '1 round',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Communicate with a creature whose mind is on the Astral Plane while its body remains.',
    description: 'This spell allows two-way communication with one creature whose astral self is currently projecting while its physical body remains behind. The physical body must be touched to establish contact. Communication lasts for 1 round per level. The astral traveler hears and can respond, but neither party can force the other to return.',
    spellClass: 'priest',
  },
  {
    id: 'strength-of-stone',
    name: 'Strength of Stone',
    school: 'Alteration',
    sphere: 'Elemental (Earth)',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour/level',
    castingTime: '1 round',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Grants +1d4 Strength (max 18) while caster stands on natural earth or stone.',
    description: 'The recipient gains 1d4 points of Strength (maximum of 18) for the duration, but only while in contact with natural earth or stone. If the recipient stands on wood, metal, or similar artificial surfaces, the bonus is suppressed until they return to natural ground. Material component: a pinch of dirt.',
    spellClass: 'priest',
  },
];

export function getSpellById(id: string): SpellData | undefined {
  return SPELLS.find(s => s.id === id);
}

export function getSpellByName(name: string): SpellData | undefined {
  return SPELLS.find(s => s.name.toLowerCase() === name.toLowerCase());
}
