export interface SpellData {
  id: string;
  name: string;
  school: string;
  sphere?: string;
  level: number;
  range: string;
  components: string;
  duration: string;
  castingTime: string;
  areaOfEffect: string;
  savingThrow: string;
  summary: string;
  description: string;
  spellClass: 'priest' | 'wizard' | 'all';
}

export const SPELLS: SpellData[] = [
  {
    id: 'altruism',
    name: 'Altruism',
    school: 'Alteration',
    sphere: 'Thought',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '1 round/level',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Target gains +1 to attack and saving throws when acting to protect others.',
    description: 'This spell fills the target with altruistic resolve. For the duration, the target gains a +1 bonus to attack rolls and saving throws made while defending or aiding another creature within 10 feet.',
    spellClass: 'priest',
  },
  {
    id: 'analyze-balance',
    name: 'Analyze Balance',
    school: 'Divination',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S, M',
    duration: 'Instantaneous',
    castingTime: '1 round',
    areaOfEffect: '10-yard radius',
    savingThrow: 'None',
    summary: 'Reveals whether the area tends toward Law, Chaos, Good, Evil, or is Neutral.',
    description: 'By casting this spell the priest learns the general alignment tendency of an area, creature, or object within range. The result indicates a dominant alignment force (Lawful, Chaotic, Good, Evil) or Neutral balance. It does not reveal individual alignments. Material component: a perfectly balanced scale made of silver.',
    spellClass: 'priest',
  },
  {
    id: 'astral-celerity',
    name: 'Astral Celerity',
    school: 'Alteration',
    sphere: 'Astral',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '1 turn',
    castingTime: '4',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Doubles movement rate on the Astral Plane.',
    description: 'This spell doubles the base movement rate of one creature while it is on the Astral Plane. It has no effect on the Prime Material or other planes.',
    spellClass: 'priest',
  },
  {
    id: 'battlefate',
    name: 'Battlefate',
    school: 'Divination',
    sphere: 'War',
    level: 1,
    range: '30 yards',
    components: 'V, S, M',
    duration: 'Instantaneous',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Reveals whether target will win, lose, or draw in next combat.',
    description: 'The priest perceives a brief flash of fate regarding one creature\'s next combat. The DM secretly rolls d6: 1-2 defeat, 3-4 draw/survival, 5-6 victory. The priest communicates only this omen to the target. Material component: a coin.',
    spellClass: 'priest',
  },
  {
    id: 'beastmask',
    name: 'Beastmask',
    school: 'Illusion',
    sphere: 'Animal',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 turn/level',
    castingTime: '4',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Caster appears as a non-threatening animal to real animals.',
    description: 'While under this spell, natural (non-magical) animals perceive the caster as a harmless member of their own species or a familiar animal. Animals will not attack the caster unless attacked first or under magical compulsion. Material component: a tuft of fur from the target animal type.',
    spellClass: 'priest',
  },
  {
    id: 'bless',
    name: 'Bless',
    school: 'Conjuration',
    sphere: 'All',
    level: 1,
    range: '60 yards',
    components: 'V, S, M',
    duration: '6 rounds',
    castingTime: '1 round',
    areaOfEffect: '50-ft. cube',
    savingThrow: 'None',
    summary: '+1 to attack rolls and morale for allies not yet in melee.',
    description: 'Upon uttering the Bless spell, the caster raises the morale of friendly creatures and increases their attack dice rolls by +1. The spell is ineffective on creatures already engaged in melee. The reverse, Curse, causes -1 penalty to attack rolls and morale for enemies in the area. Material component: holy water.',
    spellClass: 'priest',
  },
  {
    id: 'blessed-watchfulness',
    name: 'Blessed Watchfulness',
    school: 'Divination',
    sphere: 'Guardian',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '8 hours',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Target cannot be surprised and gains +2 to surprise rolls while on watch.',
    description: 'This spell keeps one creature alert and resistant to surprise for 8 hours—ideal for guards or sentinels. The target cannot be surprised and adds +2 to any dice rolls related to detecting intruders or ambushes.',
    spellClass: 'priest',
  },
  {
    id: 'calculate',
    name: 'Calculate',
    school: 'Divination',
    sphere: 'Numbers',
    level: 1,
    range: '0',
    components: 'V, S',
    duration: 'Instantaneous',
    castingTime: '1',
    areaOfEffect: 'Caster',
    savingThrow: 'None',
    summary: 'Instantly and accurately counts or measures one discrete quantity.',
    description: 'The priest mentally determines any single countable or measurable quantity within sight—the number of coins in a pile, exact weight of an object, number of creatures in a room, etc. The result is always accurate. Does not reveal hidden or invisible items.',
    spellClass: 'priest',
  },
  {
    id: 'call-upon-faith',
    name: 'Call Upon Faith',
    school: 'Evocation',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V',
    duration: 'Instantaneous',
    castingTime: '1',
    areaOfEffect: 'Caster',
    savingThrow: 'None',
    summary: '+3 bonus to one roll if the priest has acted in accordance with their faith recently.',
    description: 'The priest calls on divine favor for one roll (attack, saving throw, ability check, or proficiency check) immediately after casting. If the DM judges the priest has recently upheld their deity\'s tenets, the roll gains +3. If the priest has violated their faith, the spell fails and may cause -1 instead.',
    spellClass: 'priest',
  },
  {
    id: 'calm-animals',
    name: 'Calm Animals',
    school: 'Enchantment',
    sphere: 'Animal',
    level: 1,
    range: '60 yards',
    components: 'V, S',
    duration: '1 round/level',
    castingTime: '1',
    areaOfEffect: 'Up to 2d4 HD of animals',
    savingThrow: 'Neg.',
    summary: 'Calms normal animals; they stand passive and do not attack.',
    description: 'This spell soothes and pacifies normal animals (not magical beasts or trained war animals). Up to 2d4 HD worth of animals within range must save vs. spell or become calm and passive for the duration. Calmed animals will not attack unless attacked. The effect ends early if the animals are attacked or startled.',
    spellClass: 'priest',
  },
  {
    id: 'combine',
    name: 'Combine',
    school: 'Evocation',
    sphere: 'All',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: 'Special',
    castingTime: '1 round',
    areaOfEffect: 'Circle of priests',
    savingThrow: 'None',
    summary: 'Links 2–5 priests to boost one caster\'s effective level for turning or spells.',
    description: 'Two to five priests join hands in a circle; one is designated the primary caster. For each additional priest in the circle, the primary\'s effective level increases by 1 for purposes of turning undead or casting one spell. All participating priests except the primary expend their actions for the round. The circle breaks if any participant moves or is attacked.',
    spellClass: 'priest',
  },
  {
    id: 'command',
    name: 'Command',
    school: 'Enchantment',
    sphere: 'All',
    level: 1,
    range: '30 yards',
    components: 'V',
    duration: '1 round',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'Special',
    summary: 'One-word command obeyed immediately unless target has 6+ HD or INT 13+.',
    description: 'The priest utters a single word of command (e.g., "flee," "halt," "fall," "drop," "sleep"). The target must obey literally and immediately for 1 round. Creatures with 6 or more HD or Intelligence 13+ are unaffected. Undead are immune. Suicidal commands are also ignored.',
    spellClass: 'priest',
  },
  {
    id: 'courage',
    name: 'Courage',
    school: 'Enchantment',
    sphere: 'War',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '1 turn + 1 round/level',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Target is immune to fear effects and gains +1 morale bonus.',
    description: 'The recipient becomes immune to all fear effects (natural or magical) for the duration and gains a +1 bonus to morale-based rolls. Any existing fear condition is suppressed (not removed) for the duration.',
    spellClass: 'priest',
  },
  {
    id: 'create-water',
    name: 'Create Water',
    school: 'Alteration',
    sphere: 'Elemental (Water)',
    level: 1,
    range: '30 yards',
    components: 'V, S, M',
    duration: 'Permanent',
    castingTime: '1 round',
    areaOfEffect: 'Up to 27 cubic feet',
    savingThrow: 'None',
    summary: 'Creates 4 gallons of clean water per level (max 112 gallons).',
    description: 'This spell generates wholesome, drinkable water—4 gallons per caster level (maximum 112 gallons at 28th level). The water appears in an open container or on the ground. The reverse, Destroy Water, eliminates the same volume of water. Material component: a drop of water (or a pinch of dust for the reverse).',
    spellClass: 'priest',
  },
  {
    id: 'cure-light-wounds',
    name: 'Cure Light Wounds',
    school: 'Necromancy',
    sphere: 'Healing',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: 'Permanent',
    castingTime: '5',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Heals 1d8 hp. Reverse (Cause Light Wounds) inflicts 1d8 hp on touch.',
    description: 'When the priest lays hands on a creature and casts this spell, between 1 and 8 hit points of damage are healed. It will not raise the recipient above their maximum hit points. The reverse, Cause Light Wounds, inflicts 1d8 points of damage on a successful touch attack (saving throw for half).',
    spellClass: 'priest',
  },
  {
    id: 'detect-evil',
    name: 'Detect Evil',
    school: 'Divination',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S, M',
    duration: '1 turn + 5 rounds/level',
    castingTime: '1 round',
    areaOfEffect: '10 ft. × 120 ft. path',
    savingThrow: 'None',
    summary: 'Reveals evil emanations in a 10×120-ft. path ahead of caster.',
    description: 'The priest can sense evil (or good with the reverse) emanations—including enchanted objects, evil intentions, and undead—along a 10-foot-wide, 120-foot-long path. It does not reveal alignment of neutral creatures. The reverse, Detect Good, functions identically for good emanations. Material component: holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'detect-magic',
    name: 'Detect Magic',
    school: 'Divination',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S, M',
    duration: '1 turn',
    castingTime: '1 round',
    areaOfEffect: '10 ft. × 30 ft. path',
    savingThrow: 'None',
    summary: 'Detects magical radiations in a 10×30-ft. path for 1 turn.',
    description: 'The priest can detect magical radiations in the path ahead. Magical items, spell effects, and enchanted creatures glow. The priest can determine the general school of magic with a successful Intelligence check. Material component: holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'detect-poison',
    name: 'Detect Poison',
    school: 'Divination',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S, M',
    duration: '1 turn + 1 round/level',
    castingTime: '4',
    areaOfEffect: '1 creature or object',
    savingThrow: 'None',
    summary: 'Detects presence of poison in one creature or object; chance to identify type.',
    description: 'The priest can determine whether one creature or object has been poisoned or is poisonous. There is a 5% chance per level (max 75%) of identifying the specific type of poison. Material component: a yew leaf.',
    spellClass: 'priest',
  },
  {
    id: 'detect-snares-pits',
    name: 'Detect Snares & Pits',
    school: 'Divination',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S, M',
    duration: '4 rounds/level',
    castingTime: '4',
    areaOfEffect: '10 ft. wide × 40 ft. long path',
    savingThrow: 'None',
    summary: 'Reveals natural and primitive traps (pits, snares, deadfalls) within path.',
    description: 'The priest can detect all natural traps—pits, snares, deadfalls, and similar primitive devices—within the area ahead. It does not detect mechanical traps, spells, or magical wards. Material component: a piece of circlet vine.',
    spellClass: 'priest',
  },
  {
    id: 'dispel-fatigue',
    name: 'Dispel Fatigue',
    school: 'Necromancy',
    sphere: 'Healing',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: 'Permanent',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Removes fatigue; target treated as fully rested for 8 hours.',
    description: 'This spell removes the effects of physical fatigue from one creature, treating it as fully rested. Penalties from exhaustion or forced march are negated for 8 hours, after which normal fatigue resumes. It does not restore hit points or remove magical exhaustion.',
    spellClass: 'priest',
  },
  {
    id: 'emotion-read',
    name: 'Emotion Read',
    school: 'Divination',
    sphere: 'Thought',
    level: 1,
    range: '10 yards',
    components: 'V, S',
    duration: 'Instantaneous',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'Neg.',
    summary: 'Senses the dominant emotion of one creature (fear, anger, joy, etc.).',
    description: 'The caster reads the surface emotional state of one creature within range. The result is one dominant emotion (fear, rage, joy, sorrow, calm, etc.). It does not reveal thoughts or intentions. Creatures that save are unaffected and unaware of the attempt.',
    spellClass: 'priest',
  },
  {
    id: 'endure-cold-heat',
    name: 'Endure Cold/Heat',
    school: 'Alteration',
    sphere: 'Protection',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '1 hour/level',
    castingTime: '1',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Creature comfortable in temperatures from -30°F to 130°F; halves environmental damage.',
    description: 'The affected creature can endure temperatures from -30°F to 130°F without discomfort or penalty. If environmental conditions cause damage (extreme cold or heat beyond these ranges), the damage is halved. Does not protect against magical fire or cold attacks.',
    spellClass: 'priest',
  },
  {
    id: 'entangle',
    name: 'Entangle',
    school: 'Alteration',
    sphere: 'Plant',
    level: 1,
    range: '80 yards',
    components: 'V, S, M',
    duration: '1 turn',
    castingTime: '4',
    areaOfEffect: '40-ft. cube',
    savingThrow: 'Neg.',
    summary: 'Plants entwine creatures in area; failed save = entangled, movement 0.',
    description: 'Tall grass, weeds, bushes, and even trees wrap around creatures in the area. Those who fail their saving throw are entangled and cannot move. Those who succeed can move at half speed. Entangled creatures can still attack at -2 penalty. Burning the plants ends the effect. Material component: a drop of water and a piece of humus.',
    spellClass: 'priest',
  },
  {
    id: 'invisibility-to-undead',
    name: 'Invisibility to Undead',
    school: 'Abjuration',
    sphere: 'Necromantic',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '6 rounds',
    castingTime: '4',
    areaOfEffect: '1 creature',
    savingThrow: 'Special',
    summary: 'Undead with fewer than 5 HD cannot perceive the target; higher HD get a save.',
    description: 'Undead with fewer than 5 HD cannot detect or attack the target. Undead with 5–7 HD receive a saving throw to see through the effect; those with 8+ HD are unaffected. The spell ends early if the target attacks or takes hostile action. Material component: the priest\'s holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'light',
    name: 'Light',
    school: 'Alteration',
    sphere: 'Sun',
    level: 1,
    range: '120 yards',
    components: 'V, S',
    duration: '1 hour + 1 turn/level',
    castingTime: '4',
    areaOfEffect: '20-ft. radius globe',
    savingThrow: 'Special',
    summary: 'Creates a 20-ft. radius light source. Cast on eyes: blind until dispelled (save neg.).',
    description: 'This spell creates a globe of light equivalent to torchlight. It can be cast on an object or a point in space. If cast on a creature\'s eyes, that creature must save vs. spell or be blinded until the spell is dispelled. The reverse, Darkness, creates a 15-ft. radius area of magical darkness.',
    spellClass: 'priest',
  },
  {
    id: 'magical-stone',
    name: 'Magical Stone',
    school: 'Enchantment',
    sphere: 'Combat',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '30 minutes or until thrown',
    castingTime: '4',
    areaOfEffect: '3 pebbles',
    savingThrow: 'None',
    summary: 'Enchants 3 pebbles; each hits as +1 weapon dealing 1d4+1 (2d4+2 vs. undead).',
    description: 'Three small pebbles become +1 magical projectiles. Each is hurled by hand (range 30/60/90 ft.) or from a sling. Each hits for 1d4+1 points of damage (2d4+2 against undead). The enchantment ends when the pebbles are thrown or the duration expires. Material component: three small pebbles.',
    spellClass: 'priest',
  },
  {
    id: 'orison',
    name: 'Orison',
    school: 'Conjuration',
    sphere: 'All',
    level: 1,
    range: '0',
    components: 'V, S',
    duration: 'Special',
    castingTime: '1 round',
    areaOfEffect: 'Caster',
    savingThrow: 'None',
    summary: 'Minor divine prayer; grants +1 to one roll or minor miraculous effect at DM discretion.',
    description: 'A humble prayer to the priest\'s deity. The DM may grant a minor benefit—a +1 bonus to the next roll, a moment of divine insight, or a small miracle—based on how faithfully the priest has followed their deity\'s code. Overuse may result in no benefit.',
    spellClass: 'priest',
  },
  {
    id: 'protection-from-evil',
    name: 'Protection from Evil',
    school: 'Abjuration',
    sphere: 'Protection',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '3 rounds/level',
    castingTime: '4',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: '+2 AC and saves vs. evil creatures; blocks mental control; bodily contact forbidden for summoned creatures.',
    description: 'This spell creates a magical barrier around the recipient at a distance of 1 foot. The barrier moves with the recipient, providing +2 to AC and saving throws against attacks from evil or evilly aligned creatures. It also prevents bodily contact by summoned or conjured evil creatures. Material component: holy water or holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'purify-food-drink',
    name: 'Purify Food & Drink',
    school: 'Alteration',
    sphere: 'All',
    level: 1,
    range: '30 yards',
    components: 'V, S',
    duration: 'Permanent',
    castingTime: '1 round',
    areaOfEffect: '1 cubic foot/level',
    savingThrow: 'None',
    summary: 'Makes spoiled, poisoned, or contaminated food/drink safe and nutritious.',
    description: 'This spell makes spoiled, rotten, poisonous, or otherwise contaminated food and water pure and suitable for eating and drinking. It does not create food; it only purifies existing food. The reverse, Contaminate Food & Drink, poisons or spoils the same quantity of consumables.',
    spellClass: 'priest',
  },
  {
    id: 'remove-fear',
    name: 'Remove Fear',
    school: 'Abjuration',
    sphere: 'Charm',
    level: 1,
    range: '10 yards',
    components: 'V, S',
    duration: 'Special',
    castingTime: '1',
    areaOfEffect: '1 creature + 1/4 levels',
    savingThrow: 'None',
    summary: 'Removes fear; +4 to saves vs. fear for 1 hour. Reverse causes fear (save or flee 1d4 rounds).',
    description: 'This spell instills courage in the recipient, removing the effects of magical or normal fear. If the target is currently fleeing in fear, it may immediately re-save with a +4 bonus; success ends the fear. The spell also grants +4 to all saving throws against fear effects for 1 hour. The reverse, Cause Fear, causes one creature to flee in panic for 1d4 rounds (saving throw negates).',
    spellClass: 'priest',
  },
  {
    id: 'ring-of-hands',
    name: 'Ring of Hands',
    school: 'Evocation',
    sphere: 'Protection',
    level: 1,
    range: '0',
    components: 'V, S',
    duration: '1 round/level',
    castingTime: '1',
    areaOfEffect: 'Circle of casters',
    savingThrow: 'None',
    summary: 'Up to 10 priests join to create a protective circle; barrier repels undead and evil outsiders.',
    description: 'Up to 10 priests join hands and form a ring. While the ring is unbroken, a protective barrier prevents undead and summoned evil creatures from crossing into the circle. The barrier has no effect on natural evil creatures or humanoids. The ring breaks if any participant releases hands or is incapacitated.',
    spellClass: 'priest',
  },
  {
    id: 'sacred-guardian',
    name: 'Sacred Guardian',
    school: 'Divination',
    sphere: 'Guardian',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Until discharged',
    castingTime: '1 round',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Caster is instantly alerted (anywhere on same plane) when recipient is in mortal danger.',
    description: 'The priest places a magical link on one willing creature. If that creature falls to 0 hit points or is subjected to a death effect, the priest is instantly aware of the danger regardless of distance (as long as both are on the same plane). The spell is discharged after a single alert. Material component: a lock of the recipient\'s hair.',
    spellClass: 'priest',
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    school: 'Abjuration',
    sphere: 'Protection',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '2 rounds + 1 round/level',
    castingTime: '4',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Enemies must save to attack recipient; recipient cannot attack without ending effect.',
    description: 'Any opponent attempting to strike or attack the warded creature must first make a saving throw vs. spell. Failure means they cannot attack that creature this round (they may attack others). Success means the sanctuary is broken and the spell ends for that attacker. The ward ends entirely if the recipient makes any attack or casts a harmful spell. Material component: the priest\'s holy symbol and a small silver mirror.',
    spellClass: 'priest',
  },
  {
    id: 'speak-with-astral-traveler',
    name: 'Speak with Astral Traveler',
    school: 'Divination',
    sphere: 'Astral',
    level: 1,
    range: 'Touch',
    components: 'V, S',
    duration: '1 round/level',
    castingTime: '1 round',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Communicate with a creature whose mind is on the Astral Plane while its body remains.',
    description: 'This spell allows two-way communication with one creature whose astral self is currently projecting while its physical body remains behind. The physical body must be touched to establish contact. Communication lasts for 1 round per level. The astral traveler hears and can respond, but neither party can force the other to return.',
    spellClass: 'priest',
  },
  {
    id: 'strength-of-stone',
    name: 'Strength of Stone',
    school: 'Alteration',
    sphere: 'Elemental (Earth)',
    level: 1,
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour/level',
    castingTime: '1 round',
    areaOfEffect: '1 creature',
    savingThrow: 'None',
    summary: 'Grants +1d4 Strength (max 18) while caster stands on natural earth or stone.',
    description: 'The recipient gains 1d4 points of Strength (maximum of 18) for the duration, but only while in contact with natural earth or stone. If the recipient stands on wood, metal, or similar artificial surfaces, the bonus is suppressed until they return to natural ground. Material component: a pinch of dirt.',
    spellClass: 'priest',
  },

  // ── Level 2 Spells ────────────────────────────────────────────────────────

  {
    id: 'aid',
    name: 'Aid',
    school: 'Necromancy',
    sphere: 'Combat',
    level: 2,
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 round + 1 round/level',
    castingTime: '5',
    areaOfEffect: 'Creature touched',
    savingThrow: 'None',
    summary: 'Grants the target +1 to attack rolls and saving throws plus 1d8 temporary hit points that are lost before normal HP and cannot be restored by curative magic.',
    description: 'The recipient gains +1 to attack rolls and saving throws and 1d8 additional hit points above their normal maximum for the duration. These bonus hit points are lost first when damage is taken and cannot be regained by curative magic. Material components: a strip of white cloth with a sticky substance and the priest\'s holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'animal-spy',
    name: 'Animal Spy',
    school: 'Divination',
    sphere: 'Animal',
    level: 2,
    range: '10 yards',
    components: 'V, S',
    duration: '1 turn/2 levels of caster',
    castingTime: '5',
    areaOfEffect: '1 animal',
    savingThrow: 'None',
    summary: 'The caster enters a helpless trance to share all senses of one animal; the caster can end the link each round but doing so terminates the spell, and it also ends if the animal moves out of range.',
    description: 'The caster shares the senses of one normal or giant animal while lying in a helpless trance, unable to move or use their own senses. The caster may end the link at the start of any round (which immediately ends the spell), and the spell also ends if the animal travels more than 100 yards/level away. Wizard familiars may save vs. spell to negate.',
    spellClass: 'priest',
  },
  {
    id: 'astral-awareness',
    name: 'Astral Awareness',
    school: 'Divination',
    sphere: 'Astral',
    level: 2,
    range: '0',
    components: 'V, S',
    duration: '1 hr./level',
    castingTime: '5',
    areaOfEffect: 'The caster',
    savingThrow: 'None',
    summary: 'Automatically detects all astral and ethereal phenomena near the caster, grants +2 to surprise checks against such creatures, and provides a level-based chance to identify planar conduits and incoming gaze threats.',
    description: 'The caster automatically detects approaching astral and ethereal phenomena (conduits, psychic winds, color pools, etc.), has a 90% chance to see invisible color pools, a 5%/level chance to identify where a planar conduit leads, and a 5%/level chance to detect gaze-weapon creatures before entering their range. Grants +2 to surprise checks against astral or ethereal creatures.',
    spellClass: 'priest',
  },
  {
    id: 'augury',
    name: 'Augury',
    school: 'Divination',
    sphere: 'Divination',
    level: 2,
    range: '0',
    components: 'V, S, M',
    duration: 'Special',
    castingTime: '2 rounds',
    areaOfEffect: 'Special',
    savingThrow: 'None',
    summary: 'Reveals whether an action taken in the next 30 minutes will result in "weal" or "woe" with a base 70% (+1%/level) chance of a meaningful answer.',
    description: 'The priest divines whether an action within the next 30 minutes will benefit or harm the party, receiving an answer of "weal," "woe," or a cryptic indication. Base chance for a meaningful reply is 70% +1%/level. Material component: gem-inlaid sticks or dragon bones worth at least 1,000 gp (not consumed).',
    spellClass: 'priest',
  },
  {
    id: 'aura-of-comfort',
    name: 'Aura of Comfort',
    school: 'Evocation',
    sphere: 'Travelers',
    level: 2,
    range: 'Touch',
    components: 'V, S',
    duration: '1 hour/level',
    castingTime: '2',
    areaOfEffect: 'Creature touched',
    savingThrow: 'None',
    summary: 'Maintains a comfortable temperature for the recipient against nonmagical extremes (-20°F to 140°F) and blocks rain, snow, and hail; offers no protection against fire, magical weather, or elemental attacks.',
    description: 'A shimmering aura insulates the recipient from nonmagical temperatures between -20°F and 140°F, maintaining a comfortable 70°F, and blocks rain, snow, and hail. Temperatures outside this range are offset by the same number of degrees inside the aura. Offers no protection against fire damage, magical weather, or fire/cold-based attacks.',
    spellClass: 'priest',
  },
  {
    id: 'barkskin',
    name: 'Barkskin',
    school: 'Alteration',
    sphere: 'Plant',
    level: 2,
    range: 'Touch',
    components: 'V, S, M',
    duration: '4 rounds + 1 round/level',
    castingTime: '5',
    areaOfEffect: 'Creature touched',
    savingThrow: 'None',
    summary: 'Raises the target\'s base AC to 6 (improving by 1 per 4 caster levels) and grants +1 to non-magical saving throws; cannot be combined with worn armor or magical protection.',
    description: 'The target\'s skin toughens to AC 6 (AC 5 at 4th level, AC 4 at 8th, etc.), but does not stack with worn armor or magical protection. Saving throws against all attack forms except magic gain +1. Material component: a handful of oak bark plus the priest\'s holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'beastspite',
    name: 'Beastspite',
    school: 'Enchantment',
    sphere: 'Animal',
    level: 2,
    range: '10 yards',
    components: 'V, S',
    duration: '1 hour/level',
    castingTime: '5',
    areaOfEffect: '1 person',
    savingThrow: 'Neg.',
    summary: 'Curses a person so one species of normal animal instinctively hates, flees from, or attacks them; animals extremely loyal to the target become distressed rather than fully hostile.',
    description: 'The target is loathed by one chosen species of normal or giant animal: predators and guard animals attack, nonaggressive animals flee, and domesticated animals become distressed. Mounts attempt to throw the subject each round (riding proficiency check to stay seated). Wizard familiars, animal-friendship-bonded, or paladin\'s warhorse companions are not fully hostile but act nervous. Saving throw negates.',
    spellClass: 'priest',
  },
  {
    id: 'calm-chaos',
    name: 'Calm Chaos',
    school: 'Enchantment',
    sphere: 'Law',
    level: 2,
    range: '20 yards',
    components: 'V, S',
    duration: 'Special',
    castingTime: '1',
    areaOfEffect: '1d6 creatures/level',
    savingThrow: 'Special',
    summary: 'Suppresses the outward behavior of up to 1d6 creatures/level (save at -4) as long as a continuous distraction maintains their attention; inner emotions remain and resume when the distraction ends.',
    description: 'Affected creatures (save vs. spell at -4) halt their actions and are compelled to attend to a distraction provided by the priest or an ally (speech, performance, visual spell effects). Emotions are suppressed, not removed. The spell lasts as long as the distraction is uninterrupted; ceasing for one round or a more immediate event breaks it and original behavior resumes.',
    spellClass: 'priest',
  },
  {
    id: 'chant',
    name: 'Chant',
    school: 'Conjuration',
    sphere: 'All',
    level: 2,
    range: '0',
    components: 'V, S',
    duration: 'Time of chanting',
    castingTime: '2 rounds',
    areaOfEffect: '30-foot radius',
    savingThrow: 'None',
    summary: 'While the priest chants without moving, allies within 30 feet gain +1 to attacks, damage, and saves while enemies suffer -1; any interruption ends the spell; combines with the prayer spell for +2/-2.',
    description: 'While the caster remains stationary and chants, all friendly creatures within 30 feet gain +1 to attack rolls, damage rolls, and saving throws; all enemies in the area suffer -1 to the same. Any interruption (successful attack, grapple, silence spell) ends the chant instantly. Combining with a same-faith priest\'s prayer spell increases the bonus/penalty to +2/-2.',
    spellClass: 'priest',
  },
  {
    id: 'chaos-ward',
    name: 'Chaos Ward',
    school: 'Abjuration',
    sphere: 'Chaos',
    level: 2,
    range: 'Touch',
    components: 'V, S, M',
    duration: '2 rds./level',
    castingTime: '5',
    areaOfEffect: 'Creature touched',
    savingThrow: 'None',
    summary: 'Grants -1 AC in melee and -2 AC/+2 saves against direct ranged attacks and spells; directed attacks also have a chance to be automatically negated, ricocheted, or reflected back at the attacker.',
    description: 'A shimmering aura grants -1 AC in melee and -2 AC plus +2 saving throws against missiles or spells directed solely at the recipient. Additionally, roll d% (add caster\'s level) for each directed attack: 86–95 it is automatically defeated; 96–99 it ricochets to a random creature within 30 feet; 100+ it is reflected back at the originator. Area-effect spells do not trigger this. Material component: a playing card used by a chaotic rogue.',
    spellClass: 'priest',
  },
  {
    id: 'charm-person-or-mammal',
    name: 'Charm Person or Mammal',
    school: 'Enchantment',
    sphere: 'Animal',
    level: 2,
    range: '80 yards',
    components: 'V, S',
    duration: 'Special',
    castingTime: '5',
    areaOfEffect: '1 person or mammal',
    savingThrow: 'Neg.',
    summary: 'Makes one humanoid or mammal treat the caster as a trusted ally; the target retains its personality and may refuse harmful requests, and the charm ends when a periodic Intelligence-based saving throw succeeds or the caster harms the subject.',
    description: 'The target regards the caster as a trusted friend but retains its personality and may refuse self-destructive or deeply objectionable requests. The charm persists until broken by a periodic saving throw (frequency based on Intelligence: daily for 19+, every 3 months for 3 or less), a successful dispel magic, or any harmful act by the caster toward the target.',
    spellClass: 'priest',
  },
  {
    id: 'create-holy-symbol',
    name: 'Create Holy Symbol',
    school: 'Conjuration',
    sphere: 'Creation',
    level: 2,
    range: '0',
    components: 'V',
    duration: 'Permanent',
    castingTime: '2',
    areaOfEffect: 'The caster',
    savingThrow: 'None',
    summary: 'Conjures a permanent holy symbol of the caster\'s deity that functions identically to a carried symbol and can be gifted to a lower-level priest of the same faith.',
    description: 'A permanent holy symbol of the priest\'s deity appears in the caster\'s hands and may be used for spellcasting, turning undead, or any other purpose requiring a holy symbol. The caster may also give it to a lower-level priest of the same deity.',
    spellClass: 'priest',
  },
  {
    id: 'cure-moderate-wounds',
    name: 'Cure Moderate Wounds',
    school: 'Necromancy',
    sphere: 'Healing',
    level: 2,
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    castingTime: '5',
    areaOfEffect: 'Creature touched',
    savingThrow: 'None',
    summary: 'Heals 1d10+1 hit points on touch; reversed (Cause Moderate Wounds) inflicts the same amount of damage.',
    description: 'By laying on hands, the priest heals 1d10+1 points of damage. Cannot heal noncorporeal, nonliving, or extraplanar creatures. The reverse, Cause Moderate Wounds, inflicts 1d10+1 damage on a successful touch attack.',
    spellClass: 'priest',
  },
  {
    id: 'detect-charm',
    name: 'Detect Charm',
    school: 'Divination',
    sphere: 'Divination',
    level: 2,
    range: '30 yards',
    components: 'V, S',
    duration: '1 turn',
    castingTime: '1 round',
    areaOfEffect: '1 creature/round',
    savingThrow: 'None',
    summary: 'Detects charm-type compulsions on up to 10 creatures (save negates per creature) with a 5%/level chance to identify the exact type; the reverse masks all charms on one creature for 24 hours.',
    description: 'The priest examines one creature per round for charm, hypnosis, suggestion, or similar compulsion (target may save to block the reading). A caster who detects a charm has a 5%/level chance to identify its exact type; multiple simultaneous charms can be detected but not individually identified. The reverse, Undetectable Charm, masks all charms on one creature for 24 hours.',
    spellClass: 'priest',
  },
  {
    id: 'dissensions-feast',
    name: 'Dissension\'s Feast',
    school: 'Enchantment',
    sphere: 'Chaos',
    level: 2,
    range: 'Touch',
    components: 'V, S',
    duration: '5 turns + 2 turns/level',
    castingTime: '2 turns',
    areaOfEffect: 'Special',
    savingThrow: 'Neg.',
    summary: 'Enchants food during preparation so that anyone who eats it (save negates) becomes violently hostile toward all companions within minutes, with no memory of why after the spell expires.',
    description: 'Cast during food preparation, the spell affects up to 10 lb./level of food. Anyone who eats the enchanted food must save vs. spell 5 rounds after eating or become violently hostile toward everyone around them, abandoning all alliances. After the spell expires, affected creatures retain anger but have no memory of why they became hostile.',
    spellClass: 'priest',
  },
  {
    id: 'draw-upon-holy-might',
    name: 'Draw Upon Holy Might',
    school: 'Invocation',
    sphere: 'Summoning',
    level: 2,
    range: '0',
    components: 'V, S, M',
    duration: '1 round/level',
    castingTime: '2',
    areaOfEffect: 'The caster',
    savingThrow: 'None',
    summary: 'Raises one ability score (STR, DEX, CON, or CHA) by +1 per 3 caster levels for the duration; when the spell ends the caster is incapacitated for 4d6 turns, halved by a Constitution check.',
    description: 'The caster channels divine power to increase one eligible ability score (Strength, Dexterity, Constitution, or Charisma) by +1 per 3 levels (max +6), with all associated stat benefits. When the spell ends the caster is nearly comatose and must rest for 4d6 turns; a successful Constitution check reduces this by 50%. Material components: the priest\'s holy symbol and holy water blessed by a high priest.',
    spellClass: 'priest',
  },
  {
    id: 'dust-devil',
    name: 'Dust Devil',
    school: 'Conjuration',
    sphere: 'Elemental (Air)',
    level: 2,
    range: '30 yards',
    components: 'V, S',
    duration: '2 rounds/level',
    castingTime: '2 rounds',
    areaOfEffect: 'Special',
    savingThrow: 'None',
    summary: 'Conjures a controllable weak air elemental (AC 4, 2 HD) that extinguishes small flames, blocks gaseous creatures, and creates a blinding dust cloud; any Air-native creature disperses it in a single hit.',
    description: 'A small whirlwind (AC 4, 2 HD, MV 180, 1d4 damage) obeys the caster but dissipates if moved more than 30 yards away. It extinguishes torches and small fires, blocks or pushes gaseous creatures, and raises a 10-ft. blinding dust cloud over loose ground. Spellcasters caught in the cloud must save vs. spell to maintain concentration. Any creature native to the Elemental Plane of Air disperses it in a single hit.',
    spellClass: 'priest',
  },
  {
    id: 'emotion-perception',
    name: 'Emotion Perception',
    school: 'Divination',
    sphere: 'War',
    level: 2,
    range: '300 yards',
    components: 'V, S, M',
    duration: 'Instantaneous',
    castingTime: '1 turn',
    areaOfEffect: 'One unit/five levels',
    savingThrow: 'None',
    summary: 'Instantly reveals the current morale rating and emotional state of one military unit per 5 caster levels within unobstructed line of sight.',
    description: 'The priest instantly learns the current morale rating and morale status of one military unit per 5 caster levels within unobstructed line of sight. The DM describes morale using the appropriate term (e.g., steady, elite). Material component: the priest\'s holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'enthrall',
    name: 'Enthrall',
    school: 'Enchantment',
    sphere: 'Charm',
    level: 2,
    range: '0',
    components: 'V, S',
    duration: 'Special',
    castingTime: '1 round',
    areaOfEffect: '90-foot radius',
    savingThrow: 'Neg.',
    summary: 'Captivates an audience within 90 feet (save negates; creatures with 4+ HD or Wis 16+ are immune) for as long as the priest continues speaking, up to one hour.',
    description: 'After speaking for one full round, the priest holds the audience\'s undivided attention as long as speaking continues (max 1 hour). Those who fail their save (unfriendly races/religions get +4) cannot act while the priest speaks and for 1d3 rounds after. Creatures with 4+ HD or Wisdom 16+ are immune. New arrivals must also save. Any successful attack on the priest or ceasing to speak ends the effect.',
    spellClass: 'priest',
  },
  {
    id: 'ethereal-barrier',
    name: 'Ethereal Barrier',
    school: 'Abjuration',
    sphere: 'Astral',
    level: 2,
    range: '120 yds.',
    components: 'V, S, M',
    duration: '1 turn/level',
    castingTime: '1 turn',
    areaOfEffect: 'Two 10 ft. squares/level',
    savingThrow: 'None',
    summary: 'Creates an invisible barrier (two 10×10-ft. squares/level) that blocks ethereal, phased, and dimension-door travel; does not stop teleportation, gates, or astral creatures.',
    description: 'The priest erects an invisible barrier arranged in any configuration, blocking passage by ethereal, phased, or dimension-door/shadow-walk travelers while they remain in the Border Ethereal. Does not block teleportation, gates, or astral travelers. Multiple priests may cooperate (total levels ×2 = squares warded). Material component: rare earths and lead compound worth 10 gp per 10×10-ft. square.',
    spellClass: 'priest',
  },
  {
    id: 'find-traps',
    name: 'Find Traps',
    school: 'Divination',
    sphere: 'Divination',
    level: 2,
    range: '30 yards',
    components: 'V, S',
    duration: '3 turns',
    castingTime: '5',
    areaOfEffect: '10-foot path',
    savingThrow: 'None',
    summary: 'Reveals all magical and mechanical traps in a 10-foot-wide directional path, showing their general nature and what triggers them but not their exact effect or how to disarm them.',
    description: 'All magical and mechanical traps in a 10-foot-wide directional path become apparent. The spell is directional; the caster must face the desired direction. The priest learns the general nature of each trap and what triggers it, but not the exact effect or how to disarm it. Natural hazards, ambushes, and inactive traps are not detected.',
    spellClass: 'priest',
  },
  {
    id: 'fire-trap',
    name: 'Fire Trap',
    school: 'Abjuration',
    sphere: 'Elemental (Fire)',
    level: 2,
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Permanent until discharged',
    castingTime: '1 turn',
    areaOfEffect: 'Object touched',
    savingThrow: '1/2',
    summary: 'Permanently wards a closeable object to explode for 1d4+1/level fire damage in a 5-foot radius when opened by an unauthorized creature (save for half); the trapped item itself is unharmed.',
    description: 'Any closeable item is warded to explode (5-ft. radius, 1d4+level fire damage, save for half) when opened by an unauthorized creature. Knock spells trigger it immediately; failed disarm attempts detonate it instantly. The caster and any attuned individual (via keyword and a hair) may open it safely. The item itself is unharmed. Material component: holly berries.',
    spellClass: 'priest',
  },
  {
    id: 'flame-blade',
    name: 'Flame Blade',
    school: 'Evocation',
    sphere: 'Elemental (Fire)',
    level: 2,
    range: '0',
    components: 'V, S, M',
    duration: '4 rounds + 1 round/2 levels',
    castingTime: '4',
    areaOfEffect: '3\' long, sword-like blade',
    savingThrow: 'None',
    summary: 'Creates a scimitar-sized melee blade of fire dealing 1d4+4 damage (+2 vs. undead or fire-vulnerable, -2 vs. fire-protected); it is not a magical weapon for bypass purposes and does not function underwater.',
    description: 'A blade of fire springs from the caster\'s hand and is wielded as a scimitar, dealing 1d4+4 damage on a hit (+2 vs. undead or fire-vulnerable, -2 vs. fire-protected). Fire-using creatures take no damage. Not a magical weapon for bypass purposes (except against undead). Can ignite combustibles. Does not function underwater. Material component: a leaf of sumac.',
    spellClass: 'priest',
  },
  {
    id: 'fortifying-stew',
    name: 'Fortifying Stew',
    school: 'Necromancy',
    sphere: 'Plant',
    level: 2,
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Stew retains enchantment 1 turn',
    castingTime: '5',
    areaOfEffect: '1 bowl of stew/level',
    savingThrow: 'None',
    summary: 'Enchants cooked stew (one bowl/level) so each serving provides a full day\'s nourishment and 1d4+1 temporary hit points for 2+ hours; must be consumed within one turn of casting.',
    description: 'Up to one bowl of stew per caster level is enchanted and must be consumed within one turn. Each full serving provides a full day\'s nourishment and grants 1d4+1 temporary hit points (lost before normal HP) for 2 hours plus 1 round per caster level. Effects of multiple servings are not cumulative. Material component: a vial of stock from the first fruit of the harvest.',
    spellClass: 'priest',
  },
  {
    id: 'frisky-chest',
    name: 'Frisky Chest',
    school: 'Enchantment',
    sphere: 'Wards',
    level: 2,
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Permanent',
    castingTime: '2',
    areaOfEffect: '10-foot cube',
    savingThrow: 'None',
    summary: 'Permanently enchants a non-living object up to a 10-ft. cube to sprout appendages and flee any creature coming within 3 feet; the enchantment ends if the object is restrained for 2–5 consecutive rounds or destroyed.',
    description: 'Any nonliving object up to 10×10×10 ft. sprouts the most advantageous appendages (feet MV 21, wings Fl 24/B, or fins Sw 24) and flees any creature that comes within 3 feet, stopping once 10 feet away. It cannot attack or pass through closed openings. The enchantment ends when the caster wills it, the object is destroyed, or it is restrained for 1d4+1 consecutive rounds. Material components: a dried frog\'s leg, a feather, and a fish scale.',
    spellClass: 'priest',
  },
  {
    id: 'gift-of-speech',
    name: 'Gift of Speech',
    school: 'Enchantment',
    sphere: 'Animal',
    level: 2,
    range: '10 yards/level',
    components: 'V, S, M',
    duration: '1 turn/level',
    castingTime: '5',
    areaOfEffect: '1 animal',
    savingThrow: 'None',
    summary: 'Grants one animal the ability to speak and understand one language the caster knows for the duration; does not change the animal\'s behavior, reactions, or Intelligence.',
    description: 'One normal or giant animal gains the ability to speak and understand one language the caster knows. Its Intelligence, reactions, and behavior are unchanged. Has no effect on creatures with Intelligence less than 1. Material component: the priest\'s holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'goodberry',
    name: 'Goodberry',
    school: 'Alteration',
    sphere: 'Plant',
    level: 2,
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 day + 1 day/level',
    castingTime: '1 round',
    areaOfEffect: '2d4 fresh berries',
    savingThrow: 'None',
    summary: 'Enchants 2d4 freshly picked berries, each of which can either nourish a creature for a full day or heal 1 hit point (max 8 HP healed by berries per 24 hours); reversed (Badberry) makes 2d4 berries each deliver 1 point of poison damage.',
    description: '2d4 freshly picked berries are enchanted; each can either feed a man-sized creature for a full day or restore 1 hit point (max 8 hp healed from goodberries per 24 hours). The reverse, Badberry, makes 2d4 rotten berries appear wholesome; each delivers 1 point of poison damage (no save) if eaten. Material component: the priest\'s holy symbol passed over fresh berries.',
    spellClass: 'priest',
  },
  {
    id: 'heat-metal',
    name: 'Heat Metal',
    school: 'Alteration',
    sphere: 'Elemental (Fire)',
    level: 2,
    range: '40 yards',
    components: 'V, S, M',
    duration: '7 rounds',
    castingTime: '5',
    areaOfEffect: 'Special',
    savingThrow: 'Special',
    summary: 'Superheats ferrous metal on up to one creature per 2 caster levels over 7 rounds, escalating to 2d4 searing damage per round with a chance of physical disability; negated by fire resistance, cold, or water. Reversed (Chill Metal) freezes metal dealing up to 1d4 damage/round with a chance of numbing the hands.',
    description: 'Ferrous metal on one man-sized creature per 2 caster levels is heated over 7 rounds: warm (no damage, rounds 1 & 7), hot (1d4, rounds 2 & 6), searing (2d4, rounds 3–5). On the last searing round the target must save vs. spell or suffer a disability (limb unusable 2d4 days, body disabled 1d4 days, head unconscious 1d4 turns). Fire resistance, water, or cold negates the effect. The reverse, Chill Metal, freezes metal for up to 1d4 damage/round and may numb the hands.',
    spellClass: 'priest',
  },
  {
    id: 'hesitation',
    name: 'Hesitation',
    school: 'Enchantment',
    sphere: 'Time',
    level: 2,
    range: '30 yards',
    components: 'V, S, M',
    duration: '1 round/level',
    castingTime: '2',
    areaOfEffect: '20-foot-radius circle',
    savingThrow: 'Neg.',
    summary: 'Up to 2–8 HD of creatures (only one 4+ HD target) that fail their saves suffer a +4 initiative penalty for a number of rounds equal to the caster\'s level, beginning the round after casting.',
    description: 'The spell affects 2–8 HD worth of creatures (only one creature of 4+ HD regardless of total rolled); those failing their save add +4 to initiative rolls for the caster\'s level in rounds, beginning the round after casting. Material component: a fragment of a turtle\'s shell.',
    spellClass: 'priest',
  },
  {
    id: 'hold-person',
    name: 'Hold Person',
    school: 'Enchantment',
    sphere: 'Charm',
    level: 2,
    range: '120 yards',
    components: 'V, S, M',
    duration: '2 rounds/level',
    castingTime: '5',
    areaOfEffect: '1d4 persons in a 20-foot cube',
    savingThrow: 'Neg.',
    summary: 'Paralyzes 1d4 man-sized humanoids for 2 rounds/level; saving throw penalties increase as fewer targets are chosen (-1 for two, -2 for one); undead are immune.',
    description: 'Up to 1d4 man-sized humans, demihumans, or humanoids are held rigidly immobile (aware but unable to move or speak). Targeting 2 creatures imposes -1 penalty to saves; targeting 1 creature imposes -2. Undead are immune. The priest may end the spell at will. Material component: a small, straight piece of iron.',
    spellClass: 'priest',
  },
  {
    id: 'idea',
    name: 'Idea',
    school: 'Divination',
    sphere: 'Thought',
    level: 2,
    range: '0',
    components: 'V, S, M',
    duration: 'Instantaneous',
    castingTime: '4',
    areaOfEffect: 'The caster',
    savingThrow: 'None',
    summary: 'Prompts the DM to remind the caster\'s player of one forgotten but relevant fact or clue; usable only once every 6 hours.',
    description: 'The DM reminds the priest\'s player of one forgotten, overlooked, or discounted fact or clue relevant to the current situation. If no forgotten facts exist, the DM may reveal new relevant information at their discretion. Cannot be cast more than once every 6 hours. Material component: a gold coin.',
    spellClass: 'priest',
  },
  {
    id: 'iron-vigil',
    name: 'Iron Vigil',
    school: 'Alteration',
    sphere: 'Guardian',
    level: 2,
    range: '0',
    components: 'V, S',
    duration: '1 week + 1 day/level',
    castingTime: '1 turn',
    areaOfEffect: 'The caster',
    savingThrow: 'None',
    summary: 'Eliminates the need for food, water, and sleep for 1 week + 1 day/level; the priest can meditate to keep watch but cannot memorize spells without normal sleep, and must eat and rest fully once the vigil ends.',
    description: 'The caster needs no food, water, or sleep and is immune to natural exposure, dehydration, and climatic extremes for the duration. Meditation replaces sleep (with +1 penalty to surprise checks) but cannot substitute for spell memorization. At the vigil\'s end the priest must eat and rest or make cumulative Constitution checks (−1 per 4 hours) or fall into a potentially fatal coma.',
    spellClass: 'priest',
  },
  {
    id: 'know-alignment',
    name: 'Know Alignment',
    school: 'Divination',
    sphere: 'Divination',
    level: 2,
    range: '10 yards',
    components: 'V, S',
    duration: '1 turn',
    castingTime: '1 round',
    areaOfEffect: '1 creature or object',
    savingThrow: 'Neg.',
    summary: 'Reads the exact alignment of one creature or object after one round of concentration (save negates); the reverse (Undetectable Alignment) hides alignment for 24 hours.',
    description: 'After one round of stationary concentration, the priest reads the exact alignment of one creature or object. Unaligned objects reveal nothing; the target may save vs. spell to negate. The reverse, Undetectable Alignment, conceals a creature\'s or object\'s alignment for 24 hours.',
    spellClass: 'priest',
  },
  {
    id: 'lighten-load',
    name: 'Lighten Load',
    school: 'Alteration',
    sphere: 'Travelers',
    level: 2,
    range: '30 yards',
    components: 'V, S, M',
    duration: '1 hour/level',
    castingTime: '2',
    areaOfEffect: '10-foot cube',
    savingThrow: 'None',
    summary: 'Halves the weight of a pile of non-magical equipment filling up to a 10-foot cube for 1 hour/level; does not affect the items\' usability or physical properties.',
    description: 'All non-magical objects in a 10-foot-cube volume weigh 50% less for the duration. The objects can be distributed among multiple characters and used normally; their mass, size, texture, and strength are unchanged. Has no effect on magical items. Material components: a feather and a slip of paper moistened by a soap bubble.',
    spellClass: 'priest',
  },
  {
    id: 'messenger',
    name: 'Messenger',
    school: 'Enchantment',
    sphere: 'Animal',
    level: 2,
    range: '20 yards/level',
    components: 'V, S',
    duration: '1 day/level',
    castingTime: '1 round',
    areaOfEffect: '1 creature',
    savingThrow: 'Neg.',
    summary: 'Compels a tiny animal (save negates) to carry a note or small item to a designated location, where it waits until the spell expires before returning to its normal activities.',
    description: 'A tiny (size T) animal of at least animal intelligence that fails its save is lured to the priest and given simple directions to carry a small item or note to a specified location, where it waits until the spell expires. Does not work on giant animals or creatures with Intelligence 5+. The intended recipient gains no communication ability.',
    spellClass: 'priest',
  },
  {
    id: 'mind-read',
    name: 'Mind Read',
    school: 'Divination',
    sphere: 'Thought',
    level: 2,
    range: '5 yards/level',
    components: 'V, S',
    duration: '1 round/level',
    castingTime: '2',
    areaOfEffect: 'Special',
    savingThrow: 'None',
    summary: 'Reads the surface thoughts of all creatures in range and deeply probes one target\'s mind, with a 20% chance to reveal character class; a wary subject under interrogation may save at -2 to resist.',
    description: 'Functions like the wizard ESP spell but also allows deep probing of one target\'s mind, always revealing the creature type and with a 20% chance of identifying character class. Against a wary subject being interrogated, the target may save at -2; success blocks the deep probe entirely. The usefulness of information scales with the subject\'s Intelligence.',
    spellClass: 'priest',
  },
  {
    id: 'moment',
    name: 'Moment',
    school: 'Divination',
    sphere: 'Numbers',
    level: 2,
    range: '0',
    components: 'V, S, M',
    duration: '1 round/level',
    castingTime: '1 round',
    areaOfEffect: '50-foot radius',
    savingThrow: 'None',
    summary: 'Each round, the priest determines the optimal moment for one other character\'s single action, granting +4 on a d20 to its success; requires full concentration and ends instantly if the priest takes damage.',
    description: 'Each round the priest advises one other character within 50 feet on the ideal moment to act, granting +4 on d20 (+20%) to one action\'s success. For initiative timing: -2 initiative but -2 to hit; for attack timing: +1 initiative penalty but +4 to hit. The priest may take no other action while concentrating; any damage breaks the spell instantly. Material component: three silver dice (not consumed).',
    spellClass: 'priest',
  },
  {
    id: 'music-of-the-spheres',
    name: 'Music of the Spheres',
    school: 'Enchantment',
    sphere: 'Numbers',
    level: 2,
    range: '50 yards',
    components: 'V, S, M',
    duration: '1 turn + 1 round/level',
    castingTime: '4',
    areaOfEffect: '20-foot-diameter circle',
    savingThrow: 'Neg.',
    summary: 'Entrances hearing creatures within 20 feet (one per 3 levels, save negates) so they cannot attack the priest and suffer -3 to saves vs. charm spells; ends immediately if the priest takes any hostile action.',
    description: 'Up to one creature per 3 caster levels within a 20-ft. diameter circle that fails its save cannot attack the priest and saves vs. charm spells at -3 for the duration. Victims must be able to hear and not deaf. The spell ends instantly if the priest takes any hostile action against a victim. Material component: three silver bows with lengths in ratio 1:4:9, each worth 100 gp (not consumed).',
    spellClass: 'priest',
  },
  {
    id: 'mystic-transfer',
    name: 'Mystic Transfer',
    school: 'Invocation',
    sphere: 'All',
    level: 2,
    range: '0',
    components: 'V, S',
    duration: '9 rounds',
    castingTime: '1 round',
    areaOfEffect: 'The caster',
    savingThrow: 'None',
    summary: 'Allows same-faith priests to relay a spell through a chain of recipients within the spell\'s own range, preserving the original caster\'s level; each link must immediately pass or release the spell within the round.',
    description: 'For 9 rounds, the caster can receive any spell from a same-religion priest within that spell\'s range. The received spell retains the original caster\'s level and must be immediately cast or relayed to another mystic-transfer priest in the same round; failing to relay causes the spell to take effect. The receiving/relaying priest cannot take any other significant action that round.',
    spellClass: 'priest',
  },
  {
    id: 'nap',
    name: 'Nap',
    school: 'Alteration',
    sphere: 'Time',
    level: 2,
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Special',
    castingTime: '2',
    areaOfEffect: 'One creature/level',
    savingThrow: 'None',
    summary: 'Puts willing creatures into a 1-hour magical sleep that counts as a full night\'s rest, restoring HP and allowing spell memorization; ineffective if used more than once per 18-hour period.',
    description: 'Willing creatures sleep for 1 hour and wake as refreshed as after 8 hours of sleep, recovering lost hit points as if fully rested and allowing wizards to memorize spells. Cannot be used more than once per 18-hour period on the same creature. Material components: a scrap of pillow ticking, a feather, and a pebble kept in a pocket for seven nights.',
    spellClass: 'priest',
  },
  {
    id: 'obscurement',
    name: 'Obscurement',
    school: 'Alteration',
    sphere: 'Weather',
    level: 2,
    range: '0',
    components: 'V, S',
    duration: '4 rounds/level',
    castingTime: '5',
    areaOfEffect: 'Special',
    savingThrow: 'None',
    summary: 'Raises a mist that reduces all vision (including infravision) to 2d4 feet in a caster-level-scaling area (10×10 ft./level, max 10 ft. tall) for 4 rounds/level; a strong wind cuts the duration by 75%.',
    description: 'A misty vapor fills a square area around the caster that grows with level (10×10 ft. at 1st, 20×20 ft. at 2nd, etc.), reducing all vision including infravision to 2d4 feet. The vapor is up to 10 ft. tall and fills confined spaces. A strong wind (such as gust of wind) cuts the duration by 75%. Does not function underwater.',
    spellClass: 'priest',
  },
  {
    id: 'produce-flame',
    name: 'Produce Flame',
    school: 'Alteration',
    sphere: 'Elemental (Fire)',
    level: 2,
    range: '0',
    components: 'V, S',
    duration: '1 round/level',
    castingTime: '5',
    areaOfEffect: 'Special',
    savingThrow: 'None',
    summary: 'Summons a torch-bright flame in the caster\'s palm that can be hurled as a short-range missile dealing 1d4+1 damage and igniting combustibles; a new flame appears each round until the spell expires.',
    description: 'A torch-bright flame appears in the caster\'s palm, harmless to the caster but capable of igniting combustibles. It can be hurled up to 40 yards as a missile (short range), dealing 1d4+1 damage and igniting combustibles in a 3-ft. diameter on impact. After throwing, a new flame immediately appears in the hand if duration remains. The caster can extinguish the magical flame at will. Does not function underwater.',
    spellClass: 'priest',
  },
  {
    id: 'rally',
    name: 'Rally',
    school: 'Enchantment',
    sphere: 'War',
    level: 2,
    range: '240 yards',
    components: 'V, S, M',
    duration: 'Instantaneous',
    castingTime: '1 turn',
    areaOfEffect: 'One unit of up to 300 individuals',
    savingThrow: 'None',
    summary: 'Grants one military unit an immediate rally check during the Magic Phase rather than waiting for the Rally Phase; casters of 12th level or higher add +1 to the roll.',
    description: 'The target unit (within line of sight) may make an immediate rally check during the Magic Phase instead of waiting for the Rally Phase. A caster of 12th level or higher grants the unit a +1 bonus to the die roll. Material component: a miniature pennant or standard representing the unit\'s cause (consumed in casting).',
    spellClass: 'priest',
  },
  {
    id: 'resist-acid-and-corrosion',
    name: 'Resist Acid and Corrosion',
    school: 'Abjuration',
    sphere: 'Protection',
    level: 2,
    range: 'Touch',
    components: 'V, S',
    duration: '1 rd./level',
    castingTime: '5',
    areaOfEffect: 'Creature touched',
    savingThrow: 'None',
    summary: 'Grants complete immunity to mild acid and halves damage from intense corrosives (black dragon breath, oozes, etc.) with a +3 bonus to saves against such attacks.',
    description: 'The recipient is completely immune to mild corrosives (gear may still be damaged). Intense acids and corrosives (black dragon breath, Melf\'s acid arrow, puddings, oozes, etc.) deal half damage; if a saving throw is also required, the target gains +3, taking half damage on a failed save or one-quarter on success.',
    spellClass: 'priest',
  },
  {
    id: 'resist-fire-resist-cold',
    name: 'Resist Fire/Resist Cold',
    school: 'Alteration',
    sphere: 'Protection',
    level: 2,
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 round/level',
    castingTime: '5',
    areaOfEffect: 'Creature touched',
    savingThrow: 'None',
    summary: 'Grants immunity to mild heat or cold and halves damage from intense fire or cold (magical or natural) with a +3 save bonus; lasts 1 round/level.',
    description: 'The recipient gains complete immunity to mild heat or cold (caster\'s choice) and +3 to saving throws against intense fire or cold sources (fireballs, dragon breath, ice storms, etc.), halving all such damage. A successful save reduces damage to one-quarter. Material component: a drop of mercury.',
    spellClass: 'priest',
  },
  {
    id: 'restore-strength',
    name: 'Restore Strength',
    school: 'Necromancy',
    sphere: 'Necromantic',
    level: 2,
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    castingTime: '5',
    areaOfEffect: 'Creature touched',
    savingThrow: 'None',
    summary: 'Instantly removes all temporary ability score penalties from magical weakening effects (chill touch, shadow drain, ray of enfeeblement, etc.); does not heal physical injury or natural fatigue.',
    description: 'All temporary ability score losses from magical weakening effects (chill touch, ray of enfeeblement, shadow or roper drain, and similar) are immediately removed. Does not repair physical injury or losses from natural causes such as exhaustion, disease, or exertion.',
    spellClass: 'priest',
  },
  {
    id: 'sanctify',
    name: 'Sanctify',
    school: 'Conjuration',
    sphere: 'All',
    level: 2,
    range: '10 yards',
    components: 'V, S, M',
    duration: 'Special',
    castingTime: '1 turn',
    areaOfEffect: '10 yd. × 10 yd. square/priest',
    savingThrow: 'None',
    summary: 'Consecrates an area granting +2 saves vs. fear/charm to same-faith allies (+1 to same-alignment allies) and -1 to enemies; priests on sanctified ground turn undead at +1 level. Reversed (Defile) inverts all effects.',
    description: 'The area is consecrated: same-faith followers gain +2 to saves vs. fear and charm; same-alignment allies gain +1; enemies on sanctified ground suffer -1. Priests on sanctified ground turn undead as one level higher. Duration is 1 round per caster level, plus 2 rounds per additional contributing priest. The reverse, Defile, inverts all bonuses and causes priests to turn undead at one level lower. Material components: holy symbol and dirt from an existing same-faith temple (or a grave for the reverse).',
    spellClass: 'priest',
  },
  {
    id: 'silence-15-radius',
    name: 'Silence, 15\' Radius',
    school: 'Alteration',
    sphere: 'Guardian',
    level: 2,
    range: '120 yards',
    components: 'V, S',
    duration: '2 rounds/level',
    castingTime: '5',
    areaOfEffect: '15-foot-radius sphere',
    savingThrow: 'None',
    summary: 'Creates a 15-foot sphere of total silence for 2 rounds/level, blocking all sound and verbal spellcasting; can be anchored to a moving creature (unwilling creatures save, shifting the effect just behind them).',
    description: 'Complete silence fills a 15-ft. radius sphere: no sound enters or leaves, conversation is impossible, and verbal spells cannot be cast. The effect is stationary unless cast on a mobile object or creature. If cast on an unwilling creature, that creature may save vs. spell; success places the sphere 1 foot behind the creature\'s position instead. Counters sound-based attacks.',
    spellClass: 'priest',
  },
  {
    id: 'slow-poison',
    name: 'Slow Poison',
    school: 'Necromancy',
    sphere: 'Healing',
    level: 2,
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour/level',
    castingTime: '1',
    areaOfEffect: 'Creature touched',
    savingThrow: 'None',
    summary: 'Halts a poison\'s progression in a victim for 1 hour/level without neutralizing it, buying time for a full cure to be applied.',
    description: 'Cast before the poison\'s onset time elapses, this spell prevents the venom from taking full effect for the duration, buying time for a neutralize poison or similar cure. The poison is not destroyed; when the spell expires the venom resumes its normal progression. Material components: the priest\'s holy symbol and a crushed garlic bud smeared on the wound.',
    spellClass: 'priest',
  },
  {
    id: 'snake-charm',
    name: 'Snake Charm',
    school: 'Enchantment',
    sphere: 'Animal',
    level: 2,
    range: '30 yards',
    components: 'V, S',
    duration: 'Special',
    castingTime: '5',
    areaOfEffect: '30-foot cube',
    savingThrow: 'None',
    summary: 'Hypnotizes snakes totaling up to the priest\'s own HP into a passive swaying state for a duration that varies by how agitated they were; also effective against ophidian monsters such as nagas and couatls.',
    description: 'The caster can charm snakes whose total HP do not exceed the caster\'s own HP into a passive, swaying trance. Duration depends on the snakes\' state: torpid (1d4+2 turns), calm (1d3 turns), or angry/attacking (1d4+4 rounds). Also affects ophidian monsters (nagas, couatls, etc.) subject to magic resistance and the HP cap.',
    spellClass: 'priest',
  },
  {
    id: 'soften-earth-and-stone',
    name: 'Soften Earth and Stone',
    school: 'Alteration',
    sphere: 'Elemental (Earth)',
    level: 2,
    range: '10 yds./level',
    components: 'V, S, M',
    duration: 'Permanent',
    castingTime: '5',
    areaOfEffect: '10-ft. square/level',
    savingThrow: 'None',
    summary: 'Permanently softens natural earth or stone (10-ft. square/level): wet earth becomes mud (halves movement, may trap), dry earth becomes loose dirt, and stone becomes soft moldable clay.',
    description: 'All natural, undressed earth or stone in the area is permanently softened 1–4 ft. deep. Wet earth becomes mud (movement 10 ft./round; save vs. paralyzation or be immobilized 1d2 rounds), dry earth becomes loose dirt (half movement, no running), and stone becomes moldable clay. Magical stone and dressed/worked stone are unaffected. Vertical cliff faces may collapse. Material component: wet clay from a master potter\'s wheel.',
    spellClass: 'priest',
  },
  {
    id: 'speak-with-animals',
    name: 'Speak with Animals',
    school: 'Alteration',
    sphere: 'Animal',
    level: 2,
    range: '0',
    components: 'V, S',
    duration: '2 rounds/level',
    castingTime: '5',
    areaOfEffect: '1 animal within 30-foot radius',
    savingThrow: 'None',
    summary: 'Allows the priest to hold a two-way conversation with any normal or giant non-mindless animal; cooperation and helpfulness are not guaranteed.',
    description: 'The priest can ask questions of and receive answers from one normal or giant non-mindless animal within 30 feet. Wary animals tend toward terseness and evasion; less intelligent animals make inane comments. Friendly or same-alignment animals may perform small favors at DM discretion. Does not work with fantastic or monster creatures.',
    spellClass: 'priest',
  },
  {
    id: 'spiritual-hammer',
    name: 'Spiritual Hammer',
    school: 'Invocation',
    sphere: 'Combat',
    level: 2,
    range: '10 yards/level',
    components: 'V, S, M',
    duration: '3 rounds + 1 round/level',
    castingTime: '5',
    areaOfEffect: 'Special',
    savingThrow: 'None',
    summary: 'Conjures a force-hammer that attacks each round at the caster\'s THAC0 (+1 per 6 levels, max +3) for war hammer damage while the priest concentrates; counts as a magical weapon.',
    description: 'A force-hammer attacks the caster\'s chosen target each round using the caster\'s THAC0 (no Strength bonuses) for war-hammer damage (1d4+1 vs. man-sized, 1d4 vs. larger), with a +1 magical bonus per 6 caster levels (max +3). The caster may switch targets each round. If magic resistance stops the first hit, the spell ends. Concentration must be maintained; dispel magic may also end it. Material component: a normal war hammer hurled toward enemies while casting (disappears).',
    spellClass: 'priest',
  },
  {
    id: 'trip',
    name: 'Trip',
    school: 'Enchantment',
    sphere: 'Plant',
    level: 2,
    range: 'Touch',
    components: 'V, S',
    duration: '1 turn/level',
    castingTime: '5',
    areaOfEffect: '1 object up to 10 feet long',
    savingThrow: 'Neg.',
    summary: 'Enchants a length of rope or similar object to trip creatures crossing it (save negates) for 1 turn/level; running creatures take damage and are stunned on hard surfaces; very large creatures are unaffected.',
    description: 'A length of vine, rope, stick, or similar object (up to 10 ft.) rises to trip any creature crossing it that fails its save. Running creatures that are tripped take 1 damage and are stunned 1d4+1 rounds on hard surfaces (stunned for only the rest of the round on soft ground). Very large creatures are unaffected. Creatures aware of the trap save at +4. The object is 80% undetectable without magical means and trips the caster too. Does not work underwater.',
    spellClass: 'priest',
  },
  {
    id: 'warp-wood',
    name: 'Warp Wood',
    school: 'Alteration',
    sphere: 'Plant',
    level: 2,
    range: '10 yards/level',
    components: 'V, S',
    duration: 'Permanent',
    castingTime: '5',
    areaOfEffect: 'Special',
    savingThrow: 'Special',
    summary: 'Permanently warps a shaft of natural wood (15-inch/level diameter), rendering missile weapons useless and melee weapons -4 to hit; can also spring doors and boards. Reversed (Straighten Wood) repairs warped wood.',
    description: 'Warps approximately a 15-inch shaft of wood up to 1-inch diameter per level (e.g., axe handle or crossbow bolts at 1st, spear shaft at 5th). Warped missiles are useless; warped melee weapons suffer -4 to attacks. Boards and planks can also be affected (springing doors, leaking hulls). Enchanted wood requires the caster to be of higher level, with 20% cumulative chance of success per level difference. The reverse, Straighten Wood, repairs warped wood.',
    spellClass: 'priest',
  },
  {
    id: 'watery-fist',
    name: 'Watery Fist',
    school: 'Conjuration',
    sphere: 'Elemental (Water)',
    level: 2,
    range: '60 yds.',
    components: 'V, S, M',
    duration: '1 rd./level',
    castingTime: '5',
    areaOfEffect: 'Special',
    savingThrow: 'None',
    summary: 'Conjures a water pseudopod from a nearby body of water that strikes with the caster\'s THAC0 for 1d6–2d8 damage (scaling by level) or constricts with escalating damage each round; AC 6, only harmed by magic, fire, or cold.',
    description: 'A water pseudopod (AC 6, 15+1 hp/level; only hurt by magical weapons, fire, or cold) extends up to 10+1 ft./level from a water source. Striking damage scales with caster level: 1d6 (levels 1–4), 1d10 (5–8), 1d12 (9–12), 2d8 (13+). If used to constrict, it deals listed damage on the first round and +1 per subsequent round automatically. Requires concentration each round. Material component: blessed water or mistletoe thrown onto the source.',
    spellClass: 'priest',
  },
  {
    id: 'withdraw',
    name: 'Withdraw',
    school: 'Alteration',
    sphere: 'Protection',
    level: 2,
    range: '0',
    components: 'V, S',
    duration: 'Special',
    castingTime: '5',
    areaOfEffect: 'The caster',
    savingThrow: 'None',
    summary: 'Slows time for the caster, granting 2 + 1 round/level of private contemplation while only 1 round passes for others; only self-healing or divination spells may be cast, and any successful attack breaks the spell.',
    description: 'The caster gains 2+1 round/level of personal contemplation time while only 1 round passes for everyone else (1 minute real time per round for the player to think). During this time the caster may only use divination spells or self-targeted healing, cannot move or become invisible, loses Dexterity/shield AC bonuses, and any successful attack immediately breaks the spell.',
    spellClass: 'priest',
  },
  {
    id: 'wyvern-watch',
    name: 'Wyvern Watch',
    school: 'Evocation',
    sphere: 'Guardian',
    level: 2,
    range: '30 yards',
    components: 'V, S, M',
    duration: '8 hours or until strike',
    castingTime: '5',
    areaOfEffect: '5-foot-radius sphere',
    savingThrow: 'Neg.',
    summary: 'Creates an invisible wyvern-shaped guardian that paralyzes the first creature to fail a save (1 round/level) upon entering the guarded zone; the spell dissipates after one successful strike or after 8 hours with no strike.',
    description: 'An insubstantial wyvern-shaped force guards an area; any creature approaching within 10 feet may be attacked. The first creature that fails its save is paralyzed for 1 round/level (freed by dispel magic, remove paralysis, or the caster). A successful save means the target was missed and the ward remains. The force dissipates after the first successful paralysis or after 8 hours. Detection chance: 90% in bright light, 30% in twilight, 0% in darkness. Material component: the priest\'s holy symbol.',
    spellClass: 'priest',
  },
  {
    id: 'zone-of-truth',
    name: 'Zone of Truth',
    school: 'Enchantment',
    sphere: 'Wards',
    level: 2,
    range: '30 yards',
    components: 'V, S, M',
    duration: '1 round/level',
    castingTime: '2',
    areaOfEffect: '5-foot square/level',
    savingThrow: 'Neg.',
    summary: 'Prevents creatures in the area (5-ft. square/level) that fail their save from speaking deliberate lies; affected creatures are aware of the compulsion and may simply refuse to answer questions.',
    description: 'Creatures in the area (5-ft. square per caster level, e.g., 20×20 ft. at 4th level) that fail their save cannot speak deliberate lies, though they are aware of the compulsion and may be evasive or refuse to answer. Once a creature leaves the area it may speak freely. Material components: the priest\'s holy symbol and a false gem (phony emerald, ruby, or diamond).',
    spellClass: 'priest',
  },
];

export function getSpellById(id: string): SpellData | undefined {
  return SPELLS.find(s => s.id === id);
}

export function getSpellByName(name: string): SpellData | undefined {
  return SPELLS.find(s => s.name.toLowerCase() === name.toLowerCase());
}
